name: Build & Deploy

on:
    workflow_run:
        workflows: ['CI']
        branches: [master]
        types:
            - completed
jobs:
    docker:
        name: Publish - Docker hub
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        timeout-minutes: 10
        env:
            REPO: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPO }}
        steps:
            - uses: actions/checkout@v4
            - name: Login to Docker Hub
              run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
            - name: Build Docker image
              run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f ./Dockerfile .
            - name: Publish Docker image
              run: docker push $REPO

    deploy:
        name: Call deploy script
        runs-on: ubuntu-latest
        needs: docker
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.1.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: ${{ secrets.SSH_COMMAND }}
