name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.commits.*.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check
        run: cargo check
      - name: Fmt
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
      - name: Build
        run: cargo build --verbose
    
